dist: xenial
os: linux
language: ruby
gemfile:
  - gemfiles/omniauth_1.gemfile
  - gemfiles/omniauth_2.gemfile
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-edge
branches:
  only:
    - master
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
jobs:
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/omniauth_1.gemfile
  allow_failures:
  - rvm: ruby-edge
